DjSFTPFileManager/urls.py
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda r: HttpResponseRedirect('connections/')),
    path('connections/', include('core.urls')),
    path('ftp-client/', include('ftp_client.urls', namespace='ftp_client')),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.SFTPConnectionList.as_view(), name='sftpconnection_list'),
    path('view/<int:pk>', views.SFTPConnectionDetail.as_view(), name='sftpconnection_detail'),
    path('new', views.SFTPConnectionCreate.as_view(), name='sftpconnection_new'),
    path('edit/<int:pk>', views.SFTPConnectionUpdate.as_view(), name='sftpconnection_edit'),
    path('delete/<int:pk>', views.SFTPConnectionDelete.as_view(), name='sftpconnection_delete'),
    path('connect/<int:pk>/', views.SFTPConnectionConnect.as_view(), name='sftpconnection_connect'),
]

core/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class SFTPConnection(models.Model):
    hostname = models.CharField(max_length=200, null=False)
    login = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    port = models.PositiveIntegerField(default=22, blank=True, null=True)

    def __str__(self):
        return self.hostname

    # # The absolute path to get the url then reverse into 'student_edit' with keyword arguments (kwargs) primary key
    # def get_absolute_url(self):
    #     return reverse('sftpconnection_edit', kwargs={'pk': self.pk})

core/forms.py
from django import forms
from .models import SFTPConnection


class CustomerForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = SFTPConnection
        fields = ('hostname', 'port', 'login', 'password')

# https://stackoverflow.com/questions/17523263/how-to-create-password-field-in-model-django

core/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, reverse
from django.views.generic import View, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core import serializers

from .models import SFTPConnection


class SFTPConnectionList(ListView):
    model = SFTPConnection


class SFTPConnectionDetail(DetailView):
    model = SFTPConnection


class SFTPConnectionCreate(CreateView):
    model = SFTPConnection
    fields = ['hostname', 'login', 'password', 'port']
    success_url = reverse_lazy('core:sftpconnection_list')


class SFTPConnectionUpdate(UpdateView):
    model = SFTPConnection
    fields = ['hostname', 'login', 'password', 'port']
    success_url = reverse_lazy('core:sftpconnection_list')


class SFTPConnectionDelete(DeleteView):
    model = SFTPConnection
    success_url = reverse_lazy('core:sftpconnection_list')


class SFTPConnectionConnect(View):
    def get(self, request, *args, **kwargs):
        request.session['sftp_connection'] = serializers.serialize("json", [SFTPConnection.objects.get(id=kwargs['pk'])])
        return HttpResponseRedirect(reverse("ftp_client:index"))

core/templates/core/sftpconnection_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

core/templates/core/sftpconnection_detail.html
<h1>SFTP Connection Detail</h1>
<h3>Hostame : {{ object.hostname }}</h3>
<h3>Port : {{ object.port }}</h3>

core/templates/core/sftpconnection_form.html
<h1>SFTP Connection Form</h1>
<form method="POST">{% csrf_token %}
    <table>
        <tr>
            <td>Hostname</td>
            <td>:</td>
            <td>{{ form.hostname }}</td>
        </tr>
        <tr>
            <td>Login</td>
            <td>:</td>
            <td>{{ form.login }}</td>
        </tr>
        <tr>
            <td>Password</td>
            <td>:</td>
            <td>{{ form.password }}</td>
        </tr>
        <tr>
            <td>Port</td>
            <td>:</td>
            <td>{{ form.port }}</td>
        </tr>
        <tr>
            <td><input type="submit" value="Save"></td>
        </tr>
    </table>
</form>

core/templates/core/sftpconnection_list.html
<h1>SFTP Connection List</h1>
<a href="{% url 'core:sftpconnection_new' %}">Create New SFTP Connection</a><br><br>
<table border="1">
    <tr>
        <th>Hostname</th>
        <th>Port</th>
        <th>Actions</th>
    </tr>
    {% for sftp_connection in object_list %}
    <tr>
        <td>{{ sftp_connection.hostname }}</td>
        <td>{{ sftp_connection.port }}</td>
        <td>
            <a href="{% url 'core:sftpconnection_detail' sftp_connection.id %}">Detail</a>
            <a href="{% url 'core:sftpconnection_edit' sftp_connection.id %}">Edit</a>
            <a href="{% url 'core:sftpconnection_delete' sftp_connection.id %}">Delete</a>
            <a href="{% url 'core:sftpconnection_connect' sftp_connection.id %}">Connect</a>
        </td>
    </tr>
    {% empty %}
    <tr><td colspan="3"><b>Data is empty! Please, add data first.</b></td></tr>
    {% endfor %}
</table>